### ISSUE TITLE
Latest Gauntlet when compiled as binary doesn't work on MacOS

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#180]
This was introduced with the addition of `"@ledgerhq/hw-transport-node-hid": "^6.20.0",` library, required for Ledger support.

```
(base) ~/D/w/w/c/c/c/c/gauntlet ❯❯❯ ./bin/gauntlet-macos                                                                                                                                                                  ✘ 130 develop ✭ ✱ ◼
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: No native build was found for platform=darwin arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.18.1
    loaded from: /snapshot/gauntlet/node_modules/usb

    at Function.path (/snapshot/gauntlet/node_modules/node-gyp-build/index.js:59:9)
    at load (/snapshot/gauntlet/node_modules/node-gyp-build/index.js:21:30)
    at Object.<anonymous> (/snapshot/gauntlet/node_modules/usb/usb.js:1:125)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:93:18)
```

**Comment by archseer** [comment]
"uses node-hid and usb" -- you might need to install `libusb` first?

https://www.npmjs.com/package/@ledgerhq/hw-transport-node-hid

**Comment by archseer** [comment]
prebuildify:

> With [prebuild](https://github.com/prebuild/prebuild)ify, all prebuilt binaries are shipped inside the package that is published to npm, which means there's no need for a separate download step like you find in prebuild. The irony of this approach is that it is faster to download all prebuilt binaries for every platform when they are bundled than it is to download a single prebuilt binary as an install script.

Looks like it's not prebuilding for M1 but then it doesn't compile it at runtime either.
